# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WM7LfMij53ce6f6X1c21sBh6aqG8Hwkq
"""

import pandas as pd

df = pd.read_csv("/content/Salary_Dataset_DataScienceLovers.csv")
df

df.info()

df.isnull().sum()

for colum in df.columns:
  if df[colum].dtype == 'object':
    df[colum] = df[colum].fillna(df[colum].mode()[0])
  else:
    df[colum] = df[colum].fillna(df[colum].mean())
print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
for colum in df.columns:
  if df[colum].dtype == 'object':
    df[colum] = label_encoder.fit_transform(df[colum])
print(df)

label_encoder = LabelEncoder()
# The columns 'Gender', 'Education', and 'Level' do not exist in the DataFrame.
# 'Job Title' was already label encoded in the previous step.
# If you intended to encode different columns, please specify them here.
# For now, this loop is commented out to prevent the KeyError.
# for colum in [ 'Gender','Education', 'Level', 'Job Title']:
#     df[colum] = label_encoder.fit_transform(df[colum])
print(df)

Superate

# Separate features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

display(X.head())
display(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize the models
models = {
    "Linear Regression": LinearRegression(),
    "SVM": SVR(),
    "K-Nearest Neighbors": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42)
}

results = {}

# Loop through each model, train, predict, and evaluate
for name, model in models.items():
    print(f"\n--- Training {name} ---")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results[name] = {'MAE': mae, 'MSE': mse, 'R2 Score': r2}

    print(f"{name} MAE: {mae:.2f}")
    print(f"{name} MSE: {mse:.2f}")
    print(f"{name} R2 Score: {r2:.2f}")

# Display all results in a DataFrame for easy comparison
results_df = pd.DataFrame(results).T
print("\n--- Model Comparison ---")
display(results_df)

import matplotlib.pyplot as plt
import seaborn as sns

# Create subplots for each metric
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Plot MAE
sns.barplot(x=results_df.index, y='MAE', data=results_df, ax=axes[0], hue=results_df.index, palette='viridis', legend=False)
axes[0].set_title('Mean Absolute Error (MAE) Comparison')
axes[0].ticklabel_format(style='plain', axis='y')
axes[0].set_ylabel('MAE')
axes[0].tick_params(axis='x', rotation=45)

# Plot MSE
sns.barplot(x=results_df.index, y='MSE', data=results_df, ax=axes[1], hue=results_df.index, palette='plasma', legend=False)
axes[1].set_title('Mean Squared Error (MSE) Comparison')
axes[1].ticklabel_format(style='plain', axis='y')
axes[1].set_ylabel('MSE')
axes[1].tick_params(axis='x', rotation=45)

# Plot R2 Score
sns.barplot(x=results_df.index, y='R2 Score', data=results_df, ax=axes[2], hue=results_df.index, palette='magma', legend=False)
axes[2].set_title('R2 Score Comparison')
axes[2].set_ylabel('R2 Score')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

import pickle

# Assuming Linear Regression is chosen as the 'best' model based on its R2 score.
# You can choose a different model if your criteria are different.
best_model_name = 'Linear Regression'
best_model = models[best_model_name]

# Save the model to a .pkl file
filename = 'best_model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"The '{best_model_name}' model has been saved as {filename}")

from google.colab import files
files.download('best_model.pkl')

"""You can now download the `best_model.pkl` file from the Colab environment.

To download it, you can use the following code:
```python
from google.colab import files
files.download('best_model.pkl')
```
"""
